version: 2

project_name: xipher

env:
  - GO111MODULE=on
  - CGO_ENABLED=1

builds:

# Builds CLI
  - id: xipher-cli
    binary: xipher
    main: ./internal/cli
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - linux_arm
      - windows_amd64
      - windows_arm64
    env:
      - CGO_ENABLED=0
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}

# Builds Web Assembly
  - id: xipher-wasm
    binary: wasm/xipher
    main: ./internal/wasm
    targets:
      - js_wasm
    env:
      - CGO_ENABLED=0
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}

# Builds Shared Libraries
  - id: xipher-shared-lib-darwin-amd64
    binary: xipher
    main: ./internal/sharedlib
    buildmode: c-shared
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}

  - id: xipher-shared-lib-darwin-arm64
    binary: xipher
    main: ./internal/sharedlib
    buildmode: c-shared
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}

  - id: xipher-shared-lib-windows-amd64
    binary: xipher
    main: ./internal/sharedlib
    buildmode: c-shared
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}

  - id: xipher-shared-lib-windows-arm64
    binary: xipher
    main: ./internal/sharedlib
    buildmode: c-shared
    goos:
      - windows
    goarch:
      - arm64
    env:
      - CC=/llvm-mingw/bin/aarch64-w64-mingw32-gcc
      - CXX=/llvm-mingw/bin/aarch64-w64-mingw32-g++
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}

  - id: xipher-shared-lib-linux-amd64
    binary: xipher
    main: ./internal/sharedlib
    buildmode: c-shared
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}
      - -extldflags "-lc -lrt -lpthread"

  - id: xipher-shared-lib-linux-arm64
    binary: xipher
    main: ./internal/sharedlib
    buildmode: c-shared
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}
      - -extldflags "-lc -lrt -lpthread"

  - id: xipher-shared-lib-linux-armv7
    binary: xipher
    main: ./internal/sharedlib
    buildmode: c-shared
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    env:
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
    flags: "-mod=readonly"
    ldflags:
      - -X xipher.org/xipher.version={{.Version}}
      - -X xipher.org/xipher.commitDate={{.CommitDate}}
      - -X xipher.org/xipher.fullCommit={{.FullCommit}}
      - -X xipher.org/xipher.releaseURL={{.ReleaseURL}}
      - -extldflags "-lc -lrt -lpthread"

archives:
  - id: xipher-cli
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: [ 'zip' ]
    builds:
      - xipher-cli
  - id: xipher-wasm
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    strip_binary_directory: true
    formats: [ 'zip' ]
    files:
      - src: .ignore/wasm_exec.js
        dst: wasm_exec.js
    builds:
      - xipher-wasm
  - id: xipher-web
    name_template: xipher-web
    formats: [ 'zip' ]
    files:
      - src: .ignore/wasm_exec.js
        dst: wasm/wasm_exec.js
      - src: .ignore/web/*
        dst: .
    builds:
      - xipher-wasm
  - id: xipher-shared-lib
    name_template: "xipher-shared-lib_{{ .Os }}_{{ .Arch }}"
    formats: [ 'zip' ]
    builds:
      - xipher-shared-lib-darwin-amd64
      - xipher-shared-lib-darwin-arm64
      - xipher-shared-lib-windows-amd64
      - xipher-shared-lib-windows-arm64
      - xipher-shared-lib-linux-amd64
      - xipher-shared-lib-linux-arm64
      - xipher-shared-lib-linux-armv7

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - vendor: Xipher
    homepage: https://xipher.org
    maintainer: Shibly Meeran <shibme@shib.me>
    formats:
      - apk
      - deb
      - rpm

brews:
  - ids:
      - xipher-cli
    name: xipher
    homepage: https://xipher.org
    description: "Xipher is a curated collection of cryptographic primitives put together to perform key/password based asymmetric encryption."
    license: "MIT"
    commit_author:
      name: Shibly Meeran
      email: shibme@shib.me
    repository:
      owner: shibme
      name: homebrew-tap
      branch: main
      git:
        url: 'git@github.com:shibme/homebrew-tap.git'
        private_key: '{{ .Env.HOMEBREW_SSH_KEY }}'
