name: Xipher Action
description: Sets up the Xipher CLI in a GitHub Actions workflow
author: Shibly Meeran
inputs:
  version:
    description: Xipher CLI version to be installed
    required: false
    default: latest
  github-token:
    description: GitHub token (used to avoid rate limits when downloading Xipher CLI)
    required: false
    default: ${{ github.token }}
branding:
  icon: 'lock'
  color: 'blue'
runs:
  using: node20
  main: action/dist/index.js