name: Xipher
description: Sets up the Xipher CLI in a GitHub Actions workflow
author: Shibly Meeran
inputs:
  version:
    description: "Xipher version to install"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Install Xipher
      shell: bash
      run: |
        set -e
        export VERSION="${{ inputs.version }}"
        if [ "${{ inputs.version }}" == "latest" ]; then
          curl -fsSL https://xipher.org/install/install.sh | sh
        else
          if [[ ! "${VERSION}" =~ ^v ]]; then
            VERSION="v${VERSION}"
          fi
          curl -fsSL https://xipher.org/install/install.sh | sh -s "${VERSION}"
        fi
        sudo mv $HOME/.xipher/bin/xipher /usr/local/bin/
        xipher --version