name: Xipher Action
description: Sets up the Xipher CLI in a GitHub Actions workflow
author: Shibly Meeran
inputs:
  version:
    description: Version of SLV to install
    required: false
    default: latest
  github-token:
    description: GitHub token to use for downloading SLV (To avoid rate-limits)
    required: false
    default: ${{ github.token }}
branding:
  icon: 'lock'
  color: 'blue'
runs:
  using: node20
  main: action/dist/index.js