name: Publish Xipher Web

on:
  workflow_dispatch:
  workflow_call:

jobs:

  pages:
    name: Deploy Xipher Web
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Download and extract Xipher Web
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo shibme/xipher --pattern 'xipher-web.zip' --dir .
          unzip xipher-web.zip -d xipher-web
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy xipher-web --project-name=xipher --branch=main
